// ---------------- LEETCODE TASK DESCRIPTION ----------------- //
// ---------------- 389 - FIND THE DIFFERENCE ----------------- //

/* You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y" */

// ------------------------ SOLUTION -------------------------- //

// this "sorting kind of" approach will be more usefull if there will be more than one char added (with little adjustment).
// Time complexity: O(n log n) - because of sorting functions, iterating is O(n), but sorting is majority, then O(n log n)
// Space complexity: O(n)

const findTheDifference = (s: string, t:string): string => {
  const sArr = s.split("").sort()
  const tArr = t.split("").sort()
  for (let i = 0; i < t.length; i++) {
    if (sArr[i] !== tArr[i]) {
      return tArr[i]
    }
  }

  return "not found any difference"
}

// ------------------------ SOLUTION 2 ------------------------ //

// better Approach for one added character will be counting ASCII value of character, then we will get added character
// Time complexity: O(n) - one iteration through string
// Space complexity: O(1)

const findTheDifference2 = (s: string, t:string): string => {
  let charCount = t.charCodeAt(0)
  for (let i = 0; i < s.length; i++) {
      charCount += t.charCodeAt(i+1) - s.charCodeAt(i)
    }

    return String.fromCharCode(charCount)
  }

// --------------------------- LOGS --------------------------- //

console.log(findTheDifference("abcd", "abcde"))
console.log(findTheDifference("", "y"))
console.log(findTheDifference("tete", "tetae"))

// ---------------------------------------------------------- //

console.log(findTheDifference2("abcd", "abcde"))
console.log(findTheDifference2("", "y"))
console.log(findTheDifference2("tete", "tetae"))

// ----------------------- CLI COMMAND ------------------------ //

//run ts-node 389-findTheDifference.ts